# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: local
  demands:
    - agent.name -equals macAgent

variables:
  buildConfiguration: 'Release'

steps:

- script: |
    sudo brew upgrade
    sudo brew install --cask dotnet-sdk
    dotnet --version
    sudo export PATH="$PATH:/usr/local/share/dotnet"
    sudo source ~/.zshrc  # or ~/.bashrc
  displayName: 'Prepping Installation'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    restoreArguments: 'build $(buildConfiguration)'
    feedsToUse: 'select'
  displayName: 'dotnet restore $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test $(buildConfiguration)'




  

