trigger:
 branches:
  include:
    - main
pool:
 name: local
 demands:
  - agent.name -equals macAgent
variables:
  buildConfiguration: 'Release'
  output: weatherApp
stages:
  - stage: Build
    jobs:
    - job: Test-Build
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: 'test'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
            testRunTitle: 'dotnet test'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(output)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        
        
  - stage: Deploy Dev
    jobs:
      - deployment: Deploy to development
        strategy: 
         runOnce:
           deploy:
            steps:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download Artifacts'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'
        dependsOn: Build
        environment:
         name: staging
         resourceName:  ip-172-31-6-4
        
